### ISSUE TITLE
License for repository

### ISSUE THREAD

**Issue by raghavian** [tintn/vision-transformer-from-scratch#3]
Nice work with the implementation! I would like to adapt this implementation for teaching. However, there is no license file in your repository. Could you please add an appropriate license that allows derivative works such as [The Apache License](https://www.apache.org/licenses/LICENSE-2.0) or [MIT License](https://opensource.org/license/mit/)?

**Comment by tintn** [comment]
Hi Raghav, thanks for your interest in my work! I added the MIT Licence to the repo, feel free to use it for your purpose

**Comment by raghavian** [comment]
That's perfect. Much appreciated, Tin.
